/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BackgroundApata(props) {
  const { nodes, materials } = useGLTF("/ApataHorizontal.glb");
  
  return (
    <group {...props} dispose={null}>
      <mesh

        geometry={nodes.ApataHorizontal.geometry}
        material={materials.ApataHorizontal}
        rotation={[Math.PI / 2, 0, 0]}

      />
    </group>
  );
}

useGLTF.preload("/ApataHorizontal.glb");
