/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Facebook(props) {
  const { nodes, materials } = useGLTF("/facebook.glb");
  materials.Face.transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        onClick={() => window.open("https://www.facebook.com/ApataColombia", "_blank")}
        geometry={nodes["UI5-face"].geometry}
        material={materials.Face}
        position={[11, 9.914, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5,0.5]}
      />
    </group>
  );
}

useGLTF.preload("/facebook.glb");