/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Insta(props) {
  const { nodes, materials } = useGLTF("/insta.glb");
  materials.Insta.transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={() => window.open("https://www.instagram.com/apatacolombia/", "_blank")}
        castShadow
        receiveShadow
        geometry={nodes["UI6-insta"].geometry}
        material={materials.Insta}
        position={[11, 8.514, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5,0.5]}
      />
    </group>
  );
}

useGLTF.preload("/insta.glb");