/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LogoBlanco({position, clickEvent}) {
  const { nodes, materials } = useGLTF("/logo-blanco.glb");
  materials.Logo.transparent = true;
  return (
    <group dispose={null}>
      <mesh
        onClick={()=> clickEvent()}
        castShadow
        receiveShadow
        geometry={nodes["Logo-blanco"].geometry}
        material={materials.Logo}
        position={position}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={1.737}
      />
    </group>
  );
}

useGLTF.preload("/logo-blanco.glb");