/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LogoBlanco(props) {
  const { nodes, materials } = useGLTF("/logo-blanco.glb");
  //materials.Logo.transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Logo-blanco"].geometry}
        material={materials.Logo}
        position={[-13, 12.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.737}
      />
    </group>
  );
}

useGLTF.preload("/logo-blanco.glb");