/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useFrame } from "react";
import { useGLTF } from "@react-three/drei";

export function OverlayGeo(props) {
  const { nodes, materials } = useGLTF("/UI1.glb");



  return (
    <group {...props} dispose={null}>
      <mesh

        onClick={() => window.location.href = "./plan"}
        
        castShadow
        receiveShadow
        geometry={nodes.UI1.geometry}
        material={materials.Material}
        
        
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.337]}
      />
    </group>
  );
}

useGLTF.preload("/UI1.glb");