/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SantaIsabelTituloBig(props) {
  const { nodes, materials } = useGLTF("/santaIsabelTituloBig.glb");
  materials["SenderoOsoBig.002"].transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        onClick={() => window.location.href = "./plan-02"}
        receiveShadow
        geometry={nodes.SantaIsabelBig.geometry}
        material={materials["SenderoOsoBig.002"]}
        position={[-1.456, 6.412,-40]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[3.927, 1, 2.216]}
      />
    </group>
  );
}

useGLTF.preload("/santaIsabelTituloBig.glb");