/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SenderoPazTituloBig(props) {
  const { nodes, materials } = useGLTF("/senderoPazTituloBig.glb");
  materials["SenderoOsoBig.003"].transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        onClick={() => window.location.href = "./plan-03"}
        receiveShadow
        geometry={nodes.SenderoPazBig.geometry}
        material={materials["SenderoOsoBig.003"]}
        position={[-1, 8.412, -60]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[3.927, 1, 2.216]}
      />
    </group>
  );
}

useGLTF.preload("/senderoPazTituloBig.glb");
