/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function StartNoSound({position, clickEvent}) {
  const { nodes, materials } = useGLTF("/StartNoSound.glb");
  materials.StartNoSound.transparent = true;
  return (
    <group dispose={null}>
      <mesh
        onClick={()=> clickEvent()}
        castShadow
        receiveShadow
        geometry={nodes.StartNoSound.geometry}
        material={materials.StartNoSound}
        position={[-4.7, 6.412, 0]}
        rotation={[-Math.PI / 2, -Math.PI, -Math.PI]}
        scale={[0.9, 1, 0.9]}
      />
    </group>
  );
}

useGLTF.preload("/StartNoSound.glb");
