/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function StartSound({position, clickEvent}) {
  const { nodes, materials } = useGLTF("/StartSound.glb");
  materials.StartSound.transparent = true;
  return (
    <group dispose={null}>
      <mesh
        onClick={()=> clickEvent()}
        castShadow
        receiveShadow
        geometry={nodes.StartSound.geometry}
        material={materials.StartSound}
        position={[-4.7, 8.412, 0]}
        rotation={[-Math.PI / 2, -Math.PI, -Math.PI]}
        scale={[0.9, 1, 0.9]}
      />
    </group>
  );
}

useGLTF.preload("/StartSound.glb");
