/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SutatausaTituloBig(props) {
  const { nodes, materials } = useGLTF("/sutatausaTituloBig.glb");
  materials["SenderoOsoBig.004"].transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        onClick={() => window.location.href = "./plan-04"}
        receiveShadow
        geometry={nodes.SutatausaBig.geometry}
        material={materials["SenderoOsoBig.004"]}
        position={[-5.456, 9.412, -80]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[3.927, 1, 2.216]}
      />
    </group>
  );
}

useGLTF.preload("/sutatausaTituloBig.glb");