/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function UIDifAlta(props) {
  const { nodes, materials } = useGLTF("/UI-dificultad-alta.glb");
  materials["Material.001"].transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={() => window.location.href = "./plan"}
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
        position={[0, 9.914, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/UI-dificultad-alta.glb");