/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Waa(props) {
  const { nodes, materials } = useGLTF("/waa.glb");
  materials.Waa.transparent = true;
  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={() => window.open("https://api.whatsapp.com/send?phone=573244529945", "_blank")}
        castShadow
        receiveShadow
        geometry={nodes["UI7-waa"].geometry}
        material={materials.Waa}
        position={[11, 7.114, 0]}
        
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5,0.5]}
      />
    </group>
  );
}

useGLTF.preload("/waa.glb");